apiVersion: plugins/v1
kind: SystemComponent
metadata:
  name: express-backend
  description: A Express backend
  author: Sneha Trivedi
  labels:
    - backend
    - express
    - server_side
  icon_toolbar_filename: ./toolbar_icon.png
  icon_node_filename: ./node_icon.png #path to node icon
spec:  
  properties:
    - name: backend_name
      description: Name of this backend.
      type: string
      default: null
  environment:
    - name: port
      description: port number
      type: integer
      default: 4000
  use_case:
    cases:
      - basic
      - basic_db
      - basic_dapr
    case_matchers:
      - condition: "databases.length > 0"
        cases:
          - basic_db
      - condition: "deploymentStackPlugins.includes('Dapr')"
        cases:
          - basic_dapr
  validations:
    max_nodes_in_diagram:
      max_nodes: 2
      on_violation: warning
    connectable_to:
      - has_tags:
          - frontend
          - backend
          - database
          - queue
          - pubsub
        on_violation: error
  
  # TODO: not yet implemented in the backend:
  file_injection_policies:
    - "*.env": null
      type: environment
      inject_at:
        - container_creation
