apiVersion: plugins/context/v1
kind: ContextDefinition
metadata:
  name: DockerComposeContextDefinition
spec:
  contextObjects:
    services:
      selector:
        getAllWithLabels:
          labels:
            - backend
            - nginx
            - database
          includeFields:
            - properties.name
            - properties.image_name
            - environment.port
            - metadata.labels
      forEach:
        contextObjects:
          dependsOn:
            selector:
              getNeighboursWithLabels:
                labels:
                  - backend
                includeFields:
                  - properties.name
                  - metadata.labels
            type: Array<object>
      type: Array<object>

    # deploymentStackPlugins is provided by default, of type: Array<string>
    # each element is the name of the deploymentStackPlugins in use

    blueprintName:
      selector:
        getBlueprintName:
      type: string
