apiVersion: plugins/context/v1
kind: GenerationPolicy
metadata:
  name: KubernetesManifestGenerationPolicy
spec:
  useContext: true

  repeatFileGeneration:
    - forEach:
        obj: services
        as: service
      template:
        useCase: 'basic'
        templateFilePath: 'kubernetes-deployment.yaml.ejs'
    
    - forEach: 
        obj: services
        as: service
      template:
        useCase: 'basic'
        templateFilePath: 'kubernetes-service.yaml.ejs'
