apiVersion: plugins/v1
kind: DeploymentStack
metadata:
  name: KubernetesManifest
  author: Souris Ash
  labels:
    - devops
    - deployment_stack
    - kubernetes
    - k8s
  description: |
    Generates kubernetes objects/resources for the system you designed.
spec:
  use_case:
    cases:
      - basic
      - with_dapr
    case_matchers:
      - condition: "deploymentStackPlugins.includes('Dapr')"
        cases:
          - with_dapr
  # ** nothing here, cricketss **