apiVersion: plugins/v1
kind: SystemComponent
metadata:
  name: MySQL-database
  description: A relational database management system.
  author: Dilip Singh
  github_url: https://github.com
  labels:
    - database
    - rdbms
    - mysql
    - backend
  icon_toolbar_filename: ./toolbar-icon.png
  icon_node_filename: ./node-icon.png

spec:
  environment:
    - name: mysql_database_name
      description: Name of this database.
      type: string
      default: mysql
    
    - name: port
      description: Name of the port
      type: integer
      default: 3306

    - name: mysql_db_user
      description: Name of the database user
      type: string
      default: mysql
    
    - name: mysql_db_password
      description: password for the mysql database
      type: string
      default: null

    - name: mysql_root_password
      description: root password for the mysql database
      type: string
      default: null

    - name: mysql_schema
      description: Name of the collection of tables
      type: string
      default: null

  validations:
    - connectable_from:
        - has_tags:
          - backend
      on_violation: error
