# This is a basic workflow to help you get started with Actions

name: CI with open source plugins repository

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Add git origin for open source repo
        run: |
          git remote add opensource https://github.com/Crafter-Plugins/crafter-plugins-repository

      # Runs a set of commands using the runners shell
      - name: Push main branch of this repo to the main branch of the open source repo
        run: |
          git checkout main
          git config --unset-all http.https://github.com/.extraheader
          git push opensource main
